### ISSUE TITLE
Installation dont work on Arch and Debian 12

### ISSUE THREAD

**Issue by solisinvictum** [justaCasualCoder/Zoneminder-InstallerScript#5]
Hey,

on Arch and Debian 12, this Script fails on multiple stages.

On Arch, because of zoneminder didnt get installed (i think line 216: su temp -- yay -S zoneminder dont work).
And on Debian the same reason, because i think bookworm-backports should be used.

At least for Debian, i testing it right now and give feedback.

**Comment by solisinvictum** [comment]
So, after few investigations, this alone only works: https://wiki.zoneminder.com/Debian_12_Bookworm_with_Zoneminder_1.36.33

**Comment by justaCasualCoder** [comment]
Debian was not working as I had not started making a Debian 12 installer.  As for Arch Linux, it seems I had ```su -u temp yay --  yay -S zoneminder```  when it should have been ```sudo -E -u temp --  yay -S zoneminder```. When testing the script with Arch, it seems there are also some other issues I need to address. I will try to fix these as soon as possible. I fixed Debian 12 in the commit 12318047ed5fd886e778ff6600be3eef1d62f98c

**Comment by justaCasualCoder** [comment]
I tried to fix Arch Linux in commit 9529faf. The original error is gone, but now I am having problems with php-intl. More specifically ,`PHP message: PHP Fatal error:  Uncaught Error: Class "IntlDateFormatter" not found in /usr/share/webapps/zoneminder/www/includes/config.php:142`

**Comment by justaCasualCoder** [comment]
Closing this - I fixed Arch Linux & Debian in commit 5280b12
